export const InjectionKeyToggleSelection = Symbol()
export const InjectionKeyClearSelection = Symbol()
export const InjectionKeyToggleDropdown = Symbol()
export const InjectionKeyToggleActiveIndex = Symbol()
export const InjectionKeyHandleSearchChange = Symbol()
export const InjectionKeyCloseDropdown = Symbol()
